# Winnining Wrestlers Entertainment

In this activity you will be taking four seperate csvs that were scraped down from a wrestling database, merging them together, and then creating charts to visualize a wrestler's wins and losses over the course of four years.

### Part 1 - Macho Merging

* You will likely need to perform three different merges over the course of this activity, changing the names of your columns as you go along.

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
# Take in all of our wrestling data and read it into pandas
wrestling_2013 = "../Resources/WWE-Data-2013.csv"
wrestling_2014 = "../Resources/WWE-Data-2014.csv"
wrestling_2015 = "../Resources/WWE-Data-2015.csv"
wrestling_2016 = "../Resources/WWE-Data-2016.csv"

wrestlers_2013_df = pd.read_csv(wrestling_2013)
wrestlers_2014_df = pd.read_csv(wrestling_2014)
wrestlers_2015_df = pd.read_csv(wrestling_2015)
wrestlers_2016_df = pd.read_csv(wrestling_2016)

In [3]:
# Merge the first two datasets on "Wrestler" so that no data is lost (should be 182 rows)
combined_wrestlers_df = pd.merge(wrestlers_2013_df, wrestlers_2014_df,
                                 how='outer', on='Wrestler')
combined_wrestlers_df.head()

         Wrestler  Wins_x  Losses_x  Draws_x  Wins_y  Losses_y  Draws_y
0    Daniel Bryan   177.0      37.0      6.0    35.0      16.0      2.0
1    Dean Ambrose    70.0     134.0      4.0   129.0      36.0      2.0
2  Antonio Cesaro    80.0     126.0      1.0     5.0      24.0      0.0
3    Seth Rollins    50.0     150.0      4.0    87.0     105.0      4.0
4     Randy Orton   129.0      63.0      8.0    33.0      87.0      5.0

In [4]:
# Rename our _x columns to "2013 Wins", "2013 Losses", and "2013 Draws"
combined_wrestlers_df = combined_wrestlers_df.rename(columns={"Wins_x":"2013 Wins",
                                                              "Losses_x":"2013 Losses",
                                                              "Draws_x":"2013 Draws"})

# Rename our _y columns to "2014 Wins", "2014 Losses", and "2014 Draws"
combined_wrestlers_df = combined_wrestlers_df.rename(columns={"Wins_y":"2014 Wins",
                                                              "Losses_y":"2014 Losses",
                                                              "Draws_y":"2014 Draws"})

combined_wrestlers_df.head()

,Wrestler,2013 Wins,2013 Losses,2013 Draws,2014 Wins,2014 Losses,2014 Draws
0,Daniel Bryan,177.0,37.0,6.0,35.0,16.0,2.0
1,Dean Ambrose,70.0,134.0,4.0,129.0,36.0,2.0
2,Antonio Cesaro,80.0,126.0,1.0,5.0,24.0,0.0
3,Seth Rollins,50.0,150.0,4.0,87.0,105.0,4.0
4,Randy Orton,129.0,63.0,8.0,33.0,87.0,5.0

In [5]:
# Merge our newly combined dataframe with the 2015 dataframe
combined_wrestlers_df = pd.merge(combined_wrestlers_df, wrestlers_2015_df, how="outer", on="Wrestler")
combined_wrestlers_df

,Wrestler,2013 Wins,2013 Losses,2013 Draws,2014 Wins,2014 Losses,2014 Draws,Wins,Losses,Draws
0,Daniel Bryan,177.0,37.0,6.0,35.0,16.0,2.0,51.0,7.0,0.0
1,Dean Ambrose,70.0,134.0,4.0,129.0,36.0,2.0,150.0,63.0,5.0
2,Antonio Cesaro,80.0,126.0,1.0,5.0,24.0,0.0,NaN,NaN,NaN
3,Seth Rollins,50.0,150.0,4.0,87.0,105.0,4.0,51.0,124.0,1.0
4,Randy Orton,129.0,63.0,8.0,33.0,87.0,5.0,81.0,10.0,1.0
5,Roman Reigns,49.0,140.0,5.0,118.0,28.0,4.0,187.0,19.0,7.0
6,Ryback,103.0,88.0,3.0,43.0,114.0,1.0,138.0,34.0,2.0
7,Damien Sandow,39.0,147.0,3.0,3.0,113.0,0.0,50.0,9.0,2.0
8,Alberto Del Rio,126.0,53.0,4.0,31.0,82.0,1.0,26.0,13.0,2.0
9,Dolph Ziggler,62.0,117.0,1.0,134.0,60.0,2.0,115.0,52.0,2.0
10,Cody Rhodes,47.0,114.0,3.0,46.0,43.0,1.0,NaN,NaN,NaN
11,Jack Swagger,56.0,96.0,2.0,49.0,123.0,1.0,65.0,65.0,0.0
12,Kofi Kingston,66.0,79.0,4.0,82.0,72.0,1.0,86.0,90.0,1.0
13,Zack Ryder,66.0,80.0,0.0,8.0,53.0,0.0,88.0,45.0,0.0
14,Brodus Clay,100.0,44.0,1.0,3.0,21.0,1.0,NaN,NaN,NaN
15,Jey Uso,85.0,54.0,1.0,139.0,42.0,4.0,37.0,28.0,1.0
16,Sheamus,110.0,25.0,5.0,141.0,29.0,2.0,58.0,86.0,1.0
17,Jimmy Uso,85.0,52.0,1.0,143.0,43.0,4.0,82.0,36.0,3.0
18,Tensai,91.0,46.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
19,Titus O'Neil,29.0,108.0,1.0,29.0,132.0,1.0,92.0,61.0,0.0
20,The Miz,61.0,71.0,5.0,40.0,92.0,1.0,17.0,115.0,1.0
21,Heath Slater,5.0,129.0,1.0,11.0,106.0,1.0,1.0,131.0,0.0
22,John Cena,127.0,6.0,1.0,141.0,23.0,0.0,125.0,11.0,0.0
23,Wade Barrett,52.0,77.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
24,Darren Young,28.0,100.0,1.0,26.0,8.0,0.0,87.0,47.0,2.0
25,R-Truth,76.0,51.0,1.0,61.0,49.0,0.0,94.0,44.0,1.0
26,Big E. Langston,51.0,75.0,1.0,19.0,4.0,1.0,NaN,NaN,NaN
27,Fandango,58.0,66.0,1.0,20.0,124.0,1.0,69.0,75.0,1.0
28,Kaitlyn,87.0,37.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
29,Justin Gabriel,61.0,62.0,1.0,3.0,53.0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
183,Kevin Owens,NaN,NaN,NaN,NaN,NaN,NaN,63.0,85.0,4.0
184,King Barrett,NaN,NaN,NaN,NaN,NaN,NaN,22.0,65.0,0.0
185,Blake,NaN,NaN,NaN,NaN,NaN,NaN,31.0,51.0,0.0
186,Murphy,NaN,NaN,NaN,NaN,NaN,NaN,32.0,50.0,0.0
187,D-Von Dudley,NaN,NaN,NaN,NaN,NaN,NaN,36.0,29.0,1.0
188,Bubba Ray Dudley,NaN,NaN,NaN,NaN,NaN,NaN,36.0,28.0,1.0
189,Braun Strowman,NaN,NaN,NaN,NaN,NaN,NaN,30.0,26.0,1.0
190,Elias Samson,NaN,NaN,NaN,NaN,NaN,NaN,12.0,38.0,1.0
191,Apollo Crews,NaN,NaN,NaN,NaN,NaN,NaN,42.0,8.0,0.0
192,Samoa Joe,NaN,NaN,NaN,NaN,NaN,NaN,36.0,11.0,1.0
193,Mike Rawlis,NaN,NaN,NaN,NaN,NaN,NaN,9.0,24.0,0.0
194,Tucker Knight,NaN,NaN,NaN,NaN,NaN,NaN,3.0,24.0,1.0
195,Nia Jax,NaN,NaN,NaN,NaN,NaN,NaN,17.0,9.0,0.0
196,Riddick Moss,NaN,NaN,NaN,NaN,NaN,NaN,8.0,17.0,0.0
197,Asuka,NaN,NaN,NaN,NaN,NaN,NaN,24.0,0.0,0.0
198,Rhyno,NaN,NaN,NaN,NaN,NaN,NaN,8.0,16.0,0.0
199,Billie Kay,NaN,NaN,NaN,NaN,NaN,NaN,5.0,15.0,1.0
200,Hugo Knox,NaN,NaN,NaN,NaN,NaN,NaN,13.0,8.0,0.0
201,Lina,NaN,NaN,NaN,NaN,NaN,NaN,9.0,11.0,0.0
202,Macho Mandow,NaN,NaN,NaN,NaN,NaN,NaN,14.0,5.0,0.0
203,Jessie McKay,NaN,NaN,NaN,NaN,NaN,NaN,1.0,17.0,0.0
204,Peyton Royce,NaN,NaN,NaN,NaN,NaN,NaN,2.0,16.0,0.0
205,Uhaa Nation,NaN,NaN,NaN,NaN,NaN,NaN,13.0,3.0,0.0
206,Devin Taylor,NaN,NaN,NaN,NaN,NaN,NaN,6.0,9.0,0.0
207,Alexander Wolfe,NaN,NaN,NaN,NaN,NaN,NaN,0.0,14.0,0.0
208,Tommy Dreamer,NaN,NaN,NaN,NaN,NaN,NaN,4.0,9.0,1.0
209,Levis Valenzuela Jr.,NaN,NaN,NaN,NaN,NaN,NaN,7.0,6.0,0.0
210,Cassie,NaN,NaN,NaN,NaN,NaN,NaN,0.0,12.0,0.0
211,Gionna Daddio,NaN,NaN,NaN,NaN,NaN,NaN,8.0,4.0,0.0
212,Tino Sabbatelli,NaN,NaN,NaN,NaN,NaN,NaN,1.0,11.0,0.0

In [6]:
# Rename "wins", "losses", and "draws" to "2015 Wins", "2015 Losses", and "2015 Draws"
combined_wrestlers_df = combined_wrestlers_df.rename(columns={"Wins":"2015 Wins","Losses":"2015 Losses","Draws":"2015 Draws"})

combined_wrestlers_df.head()

,Wrestler,2013 Wins,2013 Losses,2013 Draws,2014 Wins,2014 Losses,2014 Draws,2015 Wins,2015 Losses,2015 Draws
0,Daniel Bryan,177.0,37.0,6.0,35.0,16.0,2.0,51.0,7.0,0.0
1,Dean Ambrose,70.0,134.0,4.0,129.0,36.0,2.0,150.0,63.0,5.0
2,Antonio Cesaro,80.0,126.0,1.0,5.0,24.0,0.0,NaN,NaN,NaN
3,Seth Rollins,50.0,150.0,4.0,87.0,105.0,4.0,51.0,124.0,1.0
4,Randy Orton,129.0,63.0,8.0,33.0,87.0,5.0,81.0,10.0,1.0

In [7]:
# Merge our newly combined dataframe with the 2016 dataframe
combined_wrestlers_df = pd.merge(combined_wrestlers_df, wrestlers_2016_df, how="outer", on="Wrestler")
combined_wrestlers_df.head()

,Wrestler,2013 Wins,2013 Losses,2013 Draws,2014 Wins,2014 Losses,2014 Draws,2015 Wins,2015 Losses,2015 Draws,Wins,Losses,Draws
0,Daniel Bryan,177.0,37.0,6.0,35.0,16.0,2.0,51.0,7.0,0.0,NaN,NaN,NaN
1,Dean Ambrose,70.0,134.0,4.0,129.0,36.0,2.0,150.0,63.0,5.0,133.0,67.0,4.0
2,Antonio Cesaro,80.0,126.0,1.0,5.0,24.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Seth Rollins,50.0,150.0,4.0,87.0,105.0,4.0,51.0,124.0,1.0,39.0,75.0,4.0
4,Randy Orton,129.0,63.0,8.0,33.0,87.0,5.0,81.0,10.0,1.0,39.0,21.0,0.0

In [8]:
# Rename "wins", "losses", and "draws" to "2016 Wins", "2016 Losses", and "2016 Draws"
combined_wrestlers_df = combined_wrestlers_df.rename(columns={"Wins":"2016 Wins","Losses":"2016 Losses","Draws":"2016 Draws"})

combined_wrestlers_df.head(10)

,Wrestler,2013 Wins,2013 Losses,2013 Draws,2014 Wins,2014 Losses,2014 Draws,2015 Wins,2015 Losses,2015 Draws,2016 Wins,2016 Losses,2016 Draws
0,Daniel Bryan,177.0,37.0,6.0,35.0,16.0,2.0,51.0,7.0,0.0,NaN,NaN,NaN
1,Dean Ambrose,70.0,134.0,4.0,129.0,36.0,2.0,150.0,63.0,5.0,133.0,67.0,4.0
2,Antonio Cesaro,80.0,126.0,1.0,5.0,24.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Seth Rollins,50.0,150.0,4.0,87.0,105.0,4.0,51.0,124.0,1.0,39.0,75.0,4.0
4,Randy Orton,129.0,63.0,8.0,33.0,87.0,5.0,81.0,10.0,1.0,39.0,21.0,0.0
5,Roman Reigns,49.0,140.0,5.0,118.0,28.0,4.0,187.0,19.0,7.0,142.0,12.0,5.0
6,Ryback,103.0,88.0,3.0,43.0,114.0,1.0,138.0,34.0,2.0,37.0,17.0,1.0
7,Damien Sandow,39.0,147.0,3.0,3.0,113.0,0.0,50.0,9.0,2.0,11.0,18.0,0.0
8,Alberto Del Rio,126.0,53.0,4.0,31.0,82.0,1.0,26.0,13.0,2.0,24.0,65.0,2.0
9,Dolph Ziggler,62.0,117.0,1.0,134.0,60.0,2.0,115.0,52.0,2.0,114.0,56.0,2.0