In [1]:
# Dependencies
import pandas as pd
import numpy as np

In [2]:
# Save file path to variable
pokemon = "Resources/Pokemon.csv"

In [3]:
# Read with Pandas
pokemon_pd = pd.read_csv(pokemon)
pokemon_pd.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [4]:
# Create new table
pokemon_type = pokemon_pd[["Type 1", "HP", "Attack",
                           "Defense", "Sp. Atk", "Sp. Def", "Speed"]]
pokemon_type.head()

  Type 1  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
0  Grass  45      49       49       65       65     45
1  Grass  60      62       63       80       80     60
2  Grass  80      82       83      100      100     80
3  Grass  80     100      123      122      120     80
4   Fire  39      52       43       60       50     65

In [5]:
# Create the GroupBy object based on the "Type 1" column
pokemon_group = pokemon_type.groupby(["Type 1"])

# Calculate averages for combat stats using the .mean() method
pokemon_comparison = pokemon_group.mean()
pokemon_comparison

                 HP      Attack     Defense    Sp. Atk    Sp. Def       Speed
Type 1
Bug       56.884058   70.971014   70.724638  53.869565  64.797101   61.681159
Dark      66.806452   88.387097   70.225806  74.645161  69.516129   76.161290
Dragon    83.312500  112.125000   86.375000  96.843750  88.843750   83.031250
Electric  59.795455   69.090909   66.295455  90.022727  73.704545   84.500000
Fairy     74.117647   61.529412   65.705882  78.529412  84.705882   48.588235
Fighting  69.851852   96.777778   65.925926  53.111111  64.703704   66.074074
Fire      69.903846   84.769231   67.769231  88.980769  72.211538   74.442308
Flying    70.750000   78.750000   66.250000  94.250000  72.500000  102.500000
Ghost     64.437500   73.781250   81.187500  79.343750  76.468750   64.343750
Grass     67.271429   73.214286   70.800000  77.500000  70.428571   61.928571
Ground    73.781250   95.750000   84.843750  56.468750  62.750000   63.906250
Ice       72.000000   72.750000   71.416667  77.541667  76.291667   63.458333
Normal    77.275510   73.469388   59.846939  55.816327  63.724490   71.551020
Poison    67.250000   74.678571   68.821429  60.428571  64.392857   63.571429
Psychic   70.631579   71.456140   67.684211  98.403509  86.280702   81.491228
Rock      65.363636   92.863636  100.795455  63.340909  75.477273   55.909091
Steel     65.222222   92.703704  126.370370  67.518519  80.629630   55.259259
Water     72.062500   74.151786   72.946429  74.812500  70.517857   65.964286

In [6]:
# Total number of points
pokemon_comparison["Total"] = pokemon_comparison["HP"] + pokemon_comparison["Attack"] + pokemon_comparison["Defense"] + \
    pokemon_comparison["Sp. Atk"] + \
    pokemon_comparison["Sp. Def"] + pokemon_comparison["Speed"]

pokemon_comparison["Total"]

Type 1
Bug         378.927536
Dark        445.741935
Dragon      550.531250
Electric    443.409091
Fairy       413.176471
Fighting    416.444444
Fire        458.076923
Flying      485.000000
Ghost       439.562500
Grass       421.142857
Ground      437.500000
Ice         433.458333
Normal      401.683673
Poison      399.142857
Psychic     475.947368
Rock        453.750000
Steel       487.703704
Water       430.455357
Name: Total, dtype: float64

In [7]:
# Sort by strongest Pokemon, and reset index
strongest_pokemon = pokemon_comparison.sort_values(["Total"], ascending=False)
strongest_pokemon.reset_index(inplace=True)
strongest_pokemon

,Type 1,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total
0,Dragon,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,550.531250
1,Steel,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,487.703704
2,Flying,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,485.000000
3,Psychic,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,475.947368
4,Fire,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,458.076923
5,Rock,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,453.750000
6,Dark,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,445.741935
7,Electric,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,443.409091
8,Ghost,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,439.562500
9,Ground,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,437.500000
10,Ice,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,433.458333
11,Water,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,430.455357
12,Grass,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,421.142857
13,Fighting,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,416.444444
14,Fairy,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,413.176471
15,Normal,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,401.683673
16,Poison,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,399.142857
17,Bug,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,378.927536

In [8]:
# Save output to Excel
pokemon_comparison.to_excel("output/pokemon_rankings.xlsx", index=False)